import type { AgentPersona } from '../types';

export const PERSONAS: AgentPersona[] = [
  {
    id: 'sage',
    name: 'Sage',
    role: 'ceo',
    emoji: '👑',
    color: '#FFD700',
    description: 'Visionary CEO who decomposes goals into sprints, delegates tasks, and merges PRs.',
    skills: ['sp-brainstorming', 'sp-writing-plans', 'sp-dispatching-parallel', 'sp-verification', 'ag-product-strategy'],
    defaultRoom: 'ceo-office',
    defaultSeat: 0,
  },
  {
    id: 'nova',
    name: 'Nova',
    role: 'cto',
    emoji: '🔬',
    color: '#DC143C',
    description: 'Technical guardian who reviews architecture, enforces security standards, and monitors system health.',
    skills: ['sp-requesting-review', 'sp-receiving-review', 'ag-security-audit', 'ag-api-design-principles', 'ag-architecture', 'ag-monitoring-observability'],
    defaultRoom: 'cto-office',
    defaultSeat: 0,
  },
  {
    id: 'aria',
    name: 'Aria',
    role: 'architect',
    emoji: '🏛️',
    color: '#B57EDC',
    description: 'System architect who designs holistic solutions spanning frontend, backend, and infrastructure.',
    skills: ['sp-writing-plans', 'sp-subagent-dev', 'ag-architecture', 'ag-api-design-principles', 'ag-database-design', 'ag-microservices-patterns'],
    defaultRoom: 'arch-lab',
    defaultSeat: 0,
  },
  {
    id: 'dex',
    name: 'Dex',
    role: 'dev-senior',
    emoji: '⚡',
    color: '#50C878',
    description: 'Senior TypeScript developer who writes clean, test-driven code. Backend specialist.',
    skills: ['sp-tdd-cycle', 'sp-tdd-red', 'sp-tdd-green', 'sp-tdd-refactor', 'sp-systematic-debugging', 'ag-clean-code', 'ag-typescript-pro', 'ag-auth-patterns'],
    defaultRoom: 'dev-bullpen',
    defaultSeat: 0,
  },
  {
    id: 'flux',
    name: 'Flux',
    role: 'dev-fullstack',
    emoji: '🌊',
    color: '#4169E1',
    description: 'Fullstack developer specializing in React, Next.js, and Tailwind.',
    skills: ['sp-tdd-cycle', 'sp-finishing-branch', 'ag-react-patterns', 'ag-nextjs-best-practices', 'ag-tailwind-design-system', 'ag-frontend-design'],
    defaultRoom: 'dev-bullpen',
    defaultSeat: 1,
  },
  {
    id: 'quinn',
    name: 'Quinn',
    role: 'qa-lead',
    emoji: '🔍',
    color: '#FF8C00',
    description: 'QA lead who writes comprehensive tests and enforces quality gates.',
    skills: ['sp-verification', 'sp-systematic-debugging', 'ag-testing-patterns', 'ag-playwright-skill', 'ag-e2e-testing', 'ag-accessibility-compliance'],
    defaultRoom: 'qa-lab',
    defaultSeat: 0,
  },
  {
    id: 'gage',
    name: 'Gage',
    role: 'devops',
    emoji: '🚀',
    color: '#20B2AA',
    description: 'DevOps engineer who manages CI/CD, Docker, Kubernetes, and deployment.',
    skills: ['sp-git-worktrees', 'ag-docker-expert', 'ag-kubernetes-architect', 'ag-terraform-skill', 'ag-cicd-automation', 'ag-github-actions-templates'],
    defaultRoom: 'qa-lab',
    defaultSeat: 1,
  },
  {
    id: 'morgan',
    name: 'Morgan',
    role: 'product-manager',
    emoji: '📋',
    color: '#FF69B4',
    description: 'Product manager who writes PRDs, prioritizes features, and tracks analytics.',
    skills: ['sp-brainstorming', 'sp-writing-plans', 'ag-product-manager-toolkit', 'ag-analytics-tracking'],
    defaultRoom: 'design-studio',
    defaultSeat: 1,
  },
  {
    id: 'uma',
    name: 'Uma',
    role: 'ux-designer',
    emoji: '🎨',
    color: '#8A2BE2',
    description: 'UX designer who creates intuitive interfaces and ensures accessibility.',
    skills: ['sp-brainstorming', 'ag-ui-ux-designer', 'ag-accessibility-compliance', 'ag-tailwind-design-system', 'ag-frontend-design'],
    defaultRoom: 'design-studio',
    defaultSeat: 0,
  },
  {
    id: 'river',
    name: 'River',
    role: 'scrum-master',
    emoji: '🌀',
    color: '#00CED1',
    description: 'Scrum master who facilitates sprints, coordinates parallel work, and runs retros.',
    skills: ['sp-dispatching-parallel', 'sp-verification', 'ag-agile-scrum', 'ag-team-collaboration-standup-notes'],
    defaultRoom: 'lounge',
    defaultSeat: 0,
  },
  {
    id: 'atlas',
    name: 'Atlas',
    role: 'data-engineer',
    emoji: '📊',
    color: '#708090',
    description: 'Data engineer who designs schemas, optimizes queries, and builds data pipelines.',
    skills: ['sp-tdd-cycle', 'ag-database-design', 'ag-postgresql', 'ag-sql-pro', 'ag-data-engineering-data-pipeline', 'ag-ai-ml'],
    defaultRoom: 'data-lab',
    defaultSeat: 0,
  },
];
